/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ujitha;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Ujitha
 */
public class ToPayments extends javax.swing.JFrame {

    /**
     * Creates new form Payments
     */
    public ToPayments() {
        initComponents();
        startup () ;
    }

    ToPayments(String from_Voucher, String remainAmount , String Nic) {
       initComponents();
       startup () ;
//        txtDate.setText(main.Date_Time.getDate());
        lblIdentity.setText(from_Voucher);
        txtNic.setText(Nic);
        txtCash.setText(remainAmount);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        lblIdentity = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtChequeNo = new javax.swing.JTextField();
        txtChequeAmount = new javax.swing.JTextField();
        txtChequeBranch = new javax.swing.JTextField();
        cmbBank = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChequeDisc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtccheque = new com.toedter.calendar.JDateChooser();
        txtdcheque = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtReciptId = new javax.swing.JTextField();
        txtReciptNo = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCurrentBalance = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbPaymentType = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCheque = new javax.swing.JTable();
        txtTotalOther = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTotalCash = new javax.swing.JTextField();
        txtTotalCheque = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTotalFull = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtUnbalance = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tPrevious = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtSettledCount = new javax.swing.JTextField();
        txtSettledAmount = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tSettled = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPaybleAmount = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDisc = new javax.swing.JTextArea();
        txtDate = new com.toedter.calendar.JDateChooser();

        jLabel3.setText("jLabel3");

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("To - Payment Recipt");
        setAlwaysOnTop(true);
        setResizable(false);

        lblIdentity.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblIdentity.setText("Money Issuing");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "cheque Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Cheque No");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Current Date");
        jLabel13.setToolTipText("date of today");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Amount");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Due Date");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Bank");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Branch");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("description");

        txtChequeNo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtChequeAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtChequeAmount.setText("0.00");

        txtChequeBranch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cmbBank.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BOC", "Sampath Bank", "People's Bank", "HNB", "Commercial Bank", "Nation Trust", "Amana", "NDB", "DFCC", "Seylan Bank", "Pan Asia", "other" }));

        txtChequeDisc.setColumns(20);
        txtChequeDisc.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtChequeDisc.setRows(5);
        jScrollPane2.setViewportView(txtChequeDisc);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("OK");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("Clear all");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("+");

        txtccheque.setDateFormatString("yyyy-MM-dd");
        txtccheque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtdcheque.setDateFormatString("yyyy-MM-dd");
        txtdcheque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdcheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtChequeNo)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtChequeAmount)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(txtChequeBranch)
                            .addComponent(txtccheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtccheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChequeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtdcheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtChequeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Recipt ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Recipt No");

        txtReciptId.setEditable(false);
        txtReciptId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtReciptNo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtNic.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Current Balance");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("NIC");

        txtCurrentBalance.setEditable(false);
        txtCurrentBalance.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCurrentBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtReciptId, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtReciptNo))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtReciptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(txtReciptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Payment Type");

        cmbPaymentType.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbPaymentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Cheque", "Other" }));
        cmbPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaymentTypeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Amount");

        txtCash.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCash.setText("0");
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });

        tCheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cheque No", "Amount", "Bank", "Due Date", "Current Date", "branch", "desc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tChequeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tCheque);

        txtTotalOther.setEditable(false);
        txtTotalOther.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTotalOther.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Total Cash Amount");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Total Cheque Amount");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Total other Amount");

        txtTotalCash.setEditable(false);
        txtTotalCash.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTotalCash.setText("0");

        txtTotalCheque.setEditable(false);
        txtTotalCheque.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTotalCheque.setText("0");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Full Amount");

        txtTotalFull.setEditable(false);
        txtTotalFull.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtTotalFull.setText("0");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Unbalance Amount");

        txtUnbalance.setEditable(false);
        txtUnbalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUnbalance.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPaymentType, 0, 211, Short.MAX_VALUE)
                            .addComponent(txtCash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTotalOther)
                                .addComponent(txtTotalCash)
                                .addComponent(txtTotalCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel24)
                                .addComponent(jLabel20))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalFull, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(txtUnbalance))
                            .addGap(8, 8, 8)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtUnbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Incomplete Vouchers"));

        tPrevious.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voucher ID", "Voucher No", "Date", "Remain Amount", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tPrevious);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton6.setText("OK");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton7.setText("Settle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("no of Settled Vouchers");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("Total Settled Amount");

        txtSettledCount.setEditable(false);
        txtSettledCount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtSettledAmount.setEditable(false);
        txtSettledAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tSettled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voucher ID", "Voucher No", "Amount", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tSettled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSettledKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tSettled);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSettledCount)
                            .addComponent(txtSettledAmount)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtSettledCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtSettledAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setText("Complete");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton9.setText("Cancel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Payable Amount");

        txtPaybleAmount.setEditable(false);
        txtPaybleAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPaybleAmount.setText("0");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("description");

        txtDisc.setColumns(20);
        txtDisc.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDisc.setRows(5);
        jScrollPane5.setViewportView(txtDisc);

        txtDate.setDateFormatString("yyyy-MM-dd");
        txtDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPaybleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblIdentity, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(lblIdentity))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPaybleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String ccdate = ((JTextField) txtccheque.getDateEditor().getUiComponent()).getText();
       String cddate = ((JTextField) txtdcheque.getDateEditor().getUiComponent()).getText();
        DefaultTableModel dtm = (DefaultTableModel) tCheque.getModel();
       Vector v = new Vector();
       v.add(txtChequeNo.getText());
        v.add(txtChequeAmount.getText());
         v.add(cmbBank.getSelectedItem());
          v.add(cddate);
           v.add(ccdate);
            v.add(txtChequeBranch.getText());
             v.add(txtChequeDisc.getText());
             
             dtm.addRow(v);
             
             txtCash.setText(txtChequeAmount.getText());
             double tot = 0 ;
             for (int i = 0; i < dtm.getRowCount(); i++) {
            tot += Double.parseDouble(dtm.getValueAt(i, 1).toString()) ;
        }
             txtTotalCheque.setText(tot+"");
             
            setfullTotal ();
                        
             setUnbalance();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(this, "Administrator login required !");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        tableLoad ();
        txtCurrentBalance.setText(main.Personal_Accounts.getBalance(txtNic.getText())+"");
        
    }//GEN-LAST:event_txtNicKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            DefaultTableModel settle = (DefaultTableModel) tPrevious.getModel();
             DefaultTableModel settled = (DefaultTableModel) tSettled.getModel();
            String voucherNo = settle.getValueAt(tPrevious.getSelectedRow(), 0).toString();
            String amount = JOptionPane.showInputDialog(this,"Voucher ID : "+voucherNo ,
                    "Enter settling amount", JOptionPane.QUESTION_MESSAGE);
            if (amount.isEmpty()) {
                throw new NumberFormatException() ;
            }
            Vector v = new Vector();
            v.add(settle.getValueAt(tPrevious.getSelectedRow(), 0));
             v.add(settle.getValueAt(tPrevious.getSelectedRow(), 1));
             v.add(amount);
             
             if (Double.parseDouble(settle.getValueAt(tPrevious.getSelectedRow()
                     ,3).toString()) == Double.parseDouble(amount)) {
                 v.add("full");
            }else if(Double.parseDouble(settle.getValueAt(tPrevious.getSelectedRow()
                     , 3).toString()) > Double.parseDouble(amount)){
                v.add("half");
        }else{
                
                v.add("Over paid");
                throw new Exception();
            }
             
             settled.addRow(v);
             
             txtSettledCount.setText(settled.getRowCount()+"");
             double tot = 0;
             for (int i = 0; i < settled.getRowCount(); i++) {
                tot += Double.parseDouble(settled.getValueAt(i, 2).toString());
            }
             txtSettledAmount.setText(tot+"");
             if (Double.parseDouble(txtSettledAmount.getText())>0) {
                jButton6.setEnabled(true);
            }
             settle.removeRow(tPrevious.getSelectedRow());
                            } 
        catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Amount !");
            e.printStackTrace();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Over Paid Invoice ! try again later");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          try {
        if (JOptionPane.showConfirmDialog(this, "Are you Sure ?" , "Confirm" , JOptionPane.OK_CANCEL_OPTION) == 0) {
         if (Double.parseDouble(txtTotalFull.getText()) >= Double.parseDouble(txtSettledAmount.getText())) {
            txtPaybleAmount.setText(txtSettledAmount.getText());
            if (!jButton5.isEnabled()) {
                jButton5.setEnabled(true);
            }
     setUnbalance();
            }
else {
            JOptionPane.showMessageDialog(this, "Payment Recipt Not enough !. Vouchers are Over Settled !");
            } }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tSettledKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSettledKeyPressed
          DefaultTableModel dtm = (DefaultTableModel) tSettled.getModel();
        try {
           if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
           
            txtSettledAmount.setText((Double.parseDouble(txtSettledAmount.getText())
                        - Double.parseDouble(dtm.getValueAt(tSettled.getSelectedRow(), 2).toString()))+"");
            txtPaybleAmount.setText((Double.parseDouble(txtPaybleAmount.getText())
                        - Double.parseDouble(dtm.getValueAt(tSettled.getSelectedRow(), 2).toString()))+"");
            txtSettledCount.setText((Integer.parseInt(txtSettledCount.getText())-1)+"");
             dtm.removeRow(tSettled.getSelectedRow());
               if (Double.parseDouble(txtSettledAmount.getText())==0) {
                   jButton6.setEnabled(false);
               }
                if (Double.parseDouble(txtPaybleAmount.getText())==0) {
                   jButton5.setEnabled(false);
               }
           }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_tSettledKeyPressed

    private void tChequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tChequeKeyPressed
           DefaultTableModel dtm = (DefaultTableModel) tCheque.getModel();
        try {
           if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
               if (JOptionPane.showConfirmDialog(this, "Are you Sure ?" , "Confirm" , JOptionPane.OK_CANCEL_OPTION) == 0) {
                txtTotalCheque.setText((Double.parseDouble(txtTotalCheque.getText())
                        -Double.parseDouble(dtm.getValueAt(tCheque.getSelectedRow(), 1).toString()))+"");
                   dtm.removeRow(tCheque.getSelectedRow()); 
                  setfullTotal();
               }
                   
           }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_tChequeKeyPressed

    private void cmbPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentTypeActionPerformed
        if (cmbPaymentType.getSelectedItem().equals("Cheque")) {
            jButton1.setEnabled(true);
            txtCash.setEditable(false);
        }else{
            jButton1.setEnabled(false);
        txtCash.setEditable(true);
        }
    }//GEN-LAST:event_cmbPaymentTypeActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        if (cmbPaymentType.getSelectedItem().equals("Cash")) {
            txtTotalCash.setText(txtCash.getText());
        }else if (cmbPaymentType.getSelectedItem().equals("Other")) {
             txtTotalOther.setText(txtCash.getText());
        }
        txtTotalFull.setText((Double.parseDouble(txtTotalCash.getText())
                     +Double.parseDouble(txtTotalCheque.getText())
                     +Double.parseDouble(txtTotalOther.getText()))+"");
        
        setUnbalance ();
    }//GEN-LAST:event_txtCashActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       txtChequeAmount.setText(null);
       txtChequeBranch.setText(null);
//       txtChequeDate.setText(null);
       txtChequeDisc.setText(null);
//       txtChequeDueDate.setText(null);
       txtChequeNo.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      String ind = ((JTextField) txtDate.getDateEditor().getUiComponent()).getText();
        ////////////From Sandeeptha
        try {
            Statement st10 = main.DB.con().createStatement();
            Statement st11 = main.DB.con().createStatement();
            ResultSet rs11=st11.executeQuery("SELECT balance FROM account ORDER BY id DESC LIMIT 1");
            double balance=0;
            while (rs11.next()) {                
                balance=rs11.getDouble(1);
            }
            st10.executeUpdate("INSERT INTO `sanasa`.`account` VALUES ('0','"+txtReciptId.getText()+"','"+txtReciptNo.getText()+"','"+ind+"',CURTIME(),"
                    + "'Money Issuing','"+cmbPaymentType.getSelectedItem().toString()+"','"+txtChequeNo.getText()+"','"+txtTotalFull.getText()+"','0.0',"+balance+"-'"+txtTotalFull.getText()+"');");
        } catch (Exception e) {
            e.printStackTrace();
        }
        ///////////
        try {
            if (Double.parseDouble(txtTotalFull.getText())== Double.parseDouble(txtPaybleAmount.getText())) {
            if (Double.parseDouble(txtTotalFull.getText())>0) {
                          DefaultTableModel dtmc = (DefaultTableModel) tCheque.getModel();
              DefaultTableModel dtms = (DefaultTableModel) tSettled.getModel();
              
             Statement st  = main.DB.con().createStatement();
             Statement st1 = main.DB.con().createStatement();
             Statement st2 = main.DB.con().createStatement();
             Statement st3 = main.DB.con().createStatement();
             Statement st4 = main.DB.con().createStatement();
             Statement st5 = main.DB.con().createStatement();
             Statement st6 = main.DB.con().createStatement();
             Statement st7 = main.DB.con().createStatement();
             Statement st8 = main.DB.con().createStatement();
             
             // add to paymnt recipt
             st.executeUpdate("INSERT INTO `sanasa`.`payment_recipt` VALUES "
                     + "('"+txtReciptId.getText()+"','"+txtReciptNo.getText()+"',"
                     + "'"+txtTotalFull.getText()+"','"+txtNic.getText()+"',"
                     + "'to','"+ind+"','"+main.Date_Time.getTime()+"')");
             
             // add to personal accounts with new balance (balance deducted)
             double bal = main.Personal_Accounts.getBalance(txtNic.getText())-Double.parseDouble(txtTotalFull.getText());
              st1.executeUpdate("INSERT INTO `sanasa`.`personal_account` VALUES "
                      + "('0','"+txtNic.getText()+"','"+main.Date_Time.getDate()+"',"
                      + "'"+main.Date_Time.getTime()+"',"
                      + "'"+bal+"','"+txtReciptId.getText()+"','payment','full',"
                      + "'"+(main.Personal_Accounts.getSequence()+1)+"','"+txtDisc.getText()+"')");
             
            // get personal account id and add to personal account details
              ResultSet rs = st7.executeQuery("SELECT id FROM `personal_account` "
                      + "WHERE `Contact_nic` = '"+txtNic.getText()+"' AND "
                      + "`recipt_type` = 'payment' AND `recipt_no` = '"+txtReciptId.getText()+"'");
              
              int paID  = 0;
              if (rs.next()) {
                paID = rs.getInt(1);
            }
              st2.executeUpdate("INSERT INTO `sanasa`.`personal_account_details`"
                      + " VALUES ('0','"+paID+"','"+txtTotalCash.getText()+"',"
                      + "'"+txtTotalCheque.getText()+"','"+txtTotalOther.getText()+"',"
                      + "'"+main.Date_Time.getDate()+"','"+main.Date_Time.getTime()+"',"
                      + "'"+txtTotalFull.getText()+"')");
                     
                    // get personal account details ID
              ResultSet rs1 = st8.executeQuery("SELECT MAX(`id`) FROM "
                      + "`personal_account_details`");
              
              int padID = 0 ;
              if (rs1.next()) {
                padID = rs1.getInt(1);
            }
                      for (int i = 0; i < dtmc.getRowCount(); i++) {
                 // add cheques
                    st3.executeUpdate("INSERT INTO `sanasa`.`cheque` VALUES "
                            + "('"+dtmc.getValueAt(i, 0)+"','"+dtmc.getValueAt(i, 1)+"',"
                            + "'"+dtmc.getValueAt(i, 4)+"','"+dtmc.getValueAt(i, 3)+"',"
                            + "'"+dtmc.getValueAt(i, 2)+"','"+dtmc.getValueAt(i, 5)+"',"
                            + "'issued','"+dtmc.getValueAt(i, 6)+"',"
                            + "'"+padID+"','"+txtNic.getText()+"')");
            }
           
             for (int i = 0; i < dtms.getRowCount(); i++) {
                 // add to payment recipt pays voucher
            st4.executeUpdate("INSERT INTO `sanasa`.`payment_recipt_pays_voucher`"
                    + " VALUES ('"+txtReciptId.getText()+"','"+txtNic.getText()+"',"
                    + "'"+dtms.getValueAt(i, 0)+"','"+dtms.getValueAt(i, 2)+"',"
                    + "'"+main.Date_Time.getDate()+"','"+main.Date_Time.getTime()+"')");
                    
                 if (dtms.getValueAt(i, 3).equals("half")) {
                    // update half voucher
                     st5.executeUpdate("UPDATE `sanasa`.`voucher` SET `Balance`"
                             + " = `balance`-'"+dtms.getValueAt(i, 2)+"',"
                             + "`Status` = 'no' WHERE `auto_id` = '"+dtms.getValueAt(i, 0)+"'");
                     
                 }else if (dtms.getValueAt(i, 3).equals("full")) {
                     // update full voucher
                     st6.executeUpdate("UPDATE `sanasa`.`voucher` SET "
                             + "`Balance` = '0',`Status` = 'yes' WHERE `auto_id` "
                             + "= '"+dtms.getValueAt(i, 0)+"'");
                 }
              }
             
             JOptionPane.showMessageDialog(this,
                        "Payment Recipt Successfully added and Voucher Settlement(s)  done ! ", 
                        "Complete" , JOptionPane.INFORMATION_MESSAGE);  
             dispose();
          
                }else{
                JOptionPane.showMessageDialog(this, "Payement Recipt is Empty !",
                        "error", JOptionPane.WARNING_MESSAGE);
            }
            }else {
                JOptionPane.showMessageDialog(this, "Payement Total and Voucher settlement(s) are not Balanced !",
                        "error", JOptionPane.WARNING_MESSAGE);
            }
            
             
        } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       tableLoad();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToPayments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbBank;
    private javax.swing.JComboBox cmbPaymentType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblIdentity;
    private javax.swing.JTable tCheque;
    private javax.swing.JTable tPrevious;
    private javax.swing.JTable tSettled;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChequeAmount;
    private javax.swing.JTextField txtChequeBranch;
    private javax.swing.JTextArea txtChequeDisc;
    private javax.swing.JTextField txtChequeNo;
    private javax.swing.JTextField txtCurrentBalance;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextArea txtDisc;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtPaybleAmount;
    private javax.swing.JTextField txtReciptId;
    private javax.swing.JTextField txtReciptNo;
    private javax.swing.JTextField txtSettledAmount;
    private javax.swing.JTextField txtSettledCount;
    private javax.swing.JTextField txtTotalCash;
    private javax.swing.JTextField txtTotalCheque;
    private javax.swing.JTextField txtTotalFull;
    private javax.swing.JTextField txtTotalOther;
    private javax.swing.JTextField txtUnbalance;
    private com.toedter.calendar.JDateChooser txtccheque;
    private com.toedter.calendar.JDateChooser txtdcheque;
    // End of variables declaration//GEN-END:variables

    ArrayList<String> id ;
    private void startup() {
          
        id = new ArrayList<String>();
      
        try {
            Statement s = main.DB.con().createStatement();
            Statement s1 = main.DB.con().createStatement();
                   
            ResultSet rs5 = s.executeQuery("SELECT `idpayment_recipt`  FROM "
                    + "`sanasa`.`payment_recipt` ORDER BY `idpayment_recipt`");
            int vid = 0 ;
            while (rs5.next()) {
               vid = rs5.getInt(1);
            }
           vid ++ ;
           txtReciptId.setText(vid+"");
            ResultSet rs = s1.executeQuery("SELECT `nic` FROM `sanasa`.`contact`");
            while (rs.next()) {
                id.add(rs.getString(1));
             
            }
 
            main.AutoComplete.setupAutoComplete(txtNic, id);
          TableColumn buying_price1 = tCheque.getColumnModel().getColumn(4);
        buying_price1.setMinWidth(0);
        buying_price1.setMaxWidth(0);
        buying_price1.setWidth(0);
        
         TableColumn buying_price = tCheque.getColumnModel().getColumn(5);
        buying_price.setMinWidth(0);
        buying_price.setMaxWidth(0);
        buying_price.setWidth(0);
        
         TableColumn buying_price2 = tCheque.getColumnModel().getColumn(6);
        buying_price2.setMinWidth(0);
        buying_price2.setMaxWidth(0);
        buying_price2.setWidth(0);
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Auto Complete Loading Error");
            e.printStackTrace();
        }
    }

    private void tableLoad() {
          DefaultTableModel dtm = (DefaultTableModel) tPrevious.getModel();
    dtm.setRowCount(0);
    
        String getVoucher = "SELECT `auto_id` , `date`,balance ,`maintotal`,no FROM "
                + "`sanasa`.`voucher` WHERE `status`='no' AND `Contact_nic`='"+txtNic.getText()+"'";
      
        try {
            Statement s1 = main.DB.con().createStatement();
                         
            ResultSet rs = s1.executeQuery(getVoucher);
            while (rs.next()) {
                Vector v = new Vector();
               
                v.add(rs.getString(1));
                 v.add(rs.getString(5));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                 v.add(rs.getString(4));
              dtm.addRow(v);
            }
            
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
        
    }

    private void setUnbalance() {
        txtUnbalance.setText((Double.parseDouble(txtTotalFull.getText())
                     -Double.parseDouble(txtPaybleAmount.getText())
                     )+"");
    }

    private void setfullTotal() {
         txtTotalFull.setText((Double.parseDouble(txtTotalCash.getText())
                     +Double.parseDouble(txtTotalCheque.getText())
                     +Double.parseDouble(txtTotalOther.getText()))+"");
    }

    
}
