/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ujitha;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ujitha
 */
public class Voucher extends javax.swing.JFrame {

    /**
     * Creates new form Voucher
     */
    public Voucher() {
        initComponents();
        startup ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMeterialID = new javax.swing.JTextField();
        txtMeterialName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtMeterialRate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMeterialQty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtProductQty = new javax.swing.JTextField();
        txtProductRate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tMain = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVoucherID = new javax.swing.JTextField();
        txtContactID = new javax.swing.JTextField();
        txtContactName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtVoucherNo = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtOtherName = new javax.swing.JTextField();
        txtOtherAmount = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tOther = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtExpenceTot = new javax.swing.JTextField();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtRemain = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPrevious = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSettledCount = new javax.swing.JTextField();
        txtSettledAmount = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tSettled = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        lblVoucherStatus = new javax.swing.JLabel();
        txtFnlSettled = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Voucher");
        setBackground(new java.awt.Color(153, 204, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("V  o  u  c  h  e  r");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Meterial"));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 145));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Meterial ID");
        jLabel5.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Meterial Name");
        jLabel6.setEnabled(false);

        txtMeterialID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMeterialID.setEnabled(false);
        txtMeterialID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMeterialIDActionPerformed(evt);
            }
        });
        txtMeterialID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMeterialIDKeyReleased(evt);
            }
        });

        txtMeterialName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMeterialName.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Add");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtMeterialRate.setEditable(false);
        txtMeterialRate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMeterialRate.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("QTY");
        jLabel11.setEnabled(false);

        txtMeterialQty.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMeterialQty.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Rate");
        jLabel10.setEnabled(false);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton11.setText("Change");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMeterialRate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMeterialQty)
                            .addComponent(txtMeterialName)
                            .addComponent(txtMeterialID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMeterialID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMeterialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMeterialRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMeterialQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Products"));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 145));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Product ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Product Name");

        txtProductID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });
        txtProductID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductIDKeyReleased(evt);
            }
        });

        txtProductName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtProductQty.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtProductRate.setEditable(false);
        txtProductRate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Product Rate");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Product Qty");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton9.setText("Change");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProductID, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtProductName)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProductQty, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtProductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        tMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Rate", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tMain.setToolTipText("duplicate row adding enable");
        tMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tMainKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tMain);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Voucher ID");

        txtVoucherID.setEditable(false);
        txtVoucherID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtContactID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtContactID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactIDActionPerformed(evt);
            }
        });
        txtContactID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactIDKeyReleased(evt);
            }
        });

        txtContactName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("NIC");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Voucher No");

        txtVoucherNo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtDate.setDateFormatString("yyyy-MM-dd");
        txtDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVoucherID, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txtVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtContactID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtContactName))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVoucherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel9)
                    .addComponent(txtContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtContactID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Products");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("Meterials");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jRadioButton1)
                .addGap(46, 46, 46)
                .addComponent(jRadioButton2)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Type");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Name (if any)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Amount");

        txtOtherName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtOtherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherNameActionPerformed(evt);
            }
        });

        txtOtherAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtOtherAmount.setText("0");

        cmbType.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Transport", "Salary", "tea / Food", "Other", "Tools" }));

        tOther.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Name", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tOther.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tOtherKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tOther);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton10.setText("+");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("Total");

        txtExpenceTot.setEditable(false);
        txtExpenceTot.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtExpenceTot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtExpenceTot.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOtherName)
                            .addComponent(txtOtherAmount)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtExpenceTot, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtOtherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOtherAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtExpenceTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalAmount.setText("0000");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Remain Amount");

        txtRemain.setEditable(false);
        txtRemain.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtRemain.setText("0");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("Settled Invoice Amount");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Complete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Incomplete Invoices"));

        tPrevious.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Invoice No", "Date", "Remain Amount", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tPrevious);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton7.setText("Settle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("no of Settled Invoices");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Total Settled Amount");

        txtSettledCount.setEditable(false);
        txtSettledCount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtSettledAmount.setEditable(false);
        txtSettledAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tSettled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Invoice No", "Amount", "type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tSettled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSettledKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tSettled);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSettledCount, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(txtSettledAmount)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSettledCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtSettledAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblVoucherStatus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblVoucherStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVoucherStatus.setText("no");

        txtFnlSettled.setEditable(false);
        txtFnlSettled.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtFnlSettled.setText("0");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel24.setText("Total Voucher Amount");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Description");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane5.setViewportView(txtDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFnlSettled, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotalAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(467, 467, 467)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVoucherStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFnlSettled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRemain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)))
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVoucherStatus)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMeterialIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMeterialIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMeterialIDActionPerformed

    private void txtOtherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherNameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       clear ();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        txtMeterialID.setEnabled(false);
        txtMeterialName.setEnabled(false);
        txtMeterialRate.setEnabled(false);
        txtMeterialQty.setEnabled(false);
        jLabel5.setEnabled(false);
        jLabel6.setEnabled(false);
        jLabel10.setEnabled(false);
        jLabel11.setEnabled(false);
        txtProductID.setEnabled(true);
        txtProductName.setEnabled(true);
        txtProductQty.setEnabled(true);
        txtProductRate.setEnabled(true);
        jLabel7.setEnabled(true);
        jLabel8.setEnabled(true);
        jLabel12.setEnabled(true);
        jLabel13.setEnabled(true);
        jButton3.setEnabled(true);
         jButton9.setEnabled(true);
        jButton1.setEnabled(false);
         jButton11.setEnabled(false);
        
        
          txtMeterialID.setText(null);
        txtMeterialName.setText(null);
        txtMeterialRate.setText(null);
        txtMeterialQty.setText(null);
        
          DefaultTableModel main  =  (DefaultTableModel) tMain.getModel();
          main.setRowCount(0);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        txtMeterialID.setEnabled(true);
        txtMeterialName.setEnabled(true);
        txtMeterialRate.setEnabled(true);
        txtMeterialQty.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel6.setEnabled(true);
        jLabel10.setEnabled(true);
        jLabel11.setEnabled(true);
        txtProductID.setEnabled(false);
        txtProductName.setEnabled(false);
        txtProductQty.setEnabled(false);
        txtProductRate.setEnabled(false);
        jLabel7.setEnabled(false);
        jLabel8.setEnabled(false);
        jLabel12.setEnabled(false);
        jLabel13.setEnabled(false);
        jButton3.setEnabled(false);
        jButton1.setEnabled(true);
         jButton9.setEnabled(false);
          jButton11.setEnabled(true);
        
         txtProductID.setText(null);
        txtProductName.setText(null);
        txtProductQty.setText(null);
        txtProductRate.setText(null);
        DefaultTableModel main  =  (DefaultTableModel) tMain.getModel();
          main.setRowCount(0);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
double maintot  , othertot;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        try {
           DefaultTableModel main  =  (DefaultTableModel) tMain.getModel();
            Vector v = new Vector();
            v.add(txtMeterialID.getText());
            v.add(txtMeterialName.getText());
            v.add(txtMeterialQty.getText());
            v.add(txtMeterialRate.getText());
            
            v.add(Double.parseDouble(txtMeterialQty.getText()) * Double.parseDouble(txtMeterialRate.getText()));
            main.addRow(v);
            
            txtMeterialID.setText(null);
            txtMeterialName.setText(null);
            txtMeterialRate.setText(null);
            txtMeterialQty.setText(null);
            maintot = 0 ;
            for (int i = 0; i < main.getRowCount(); i++) {
                maintot += Double.parseDouble(main.getValueAt(i, 4).toString());
            }
            lblTotalAmount.setText((maintot+Double.parseDouble(txtExpenceTot.getText()))+"");
            txtRemain.setText(maintot+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Adding this record incomplete."
                    + "\nRow is not added to the table", "Incomplete", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        try {
           DefaultTableModel main  =  (DefaultTableModel) tMain.getModel();
             Vector v = new Vector();
            v.add(txtProductID.getText());
            v.add(txtProductName.getText());
            v.add(txtProductQty.getText());
            v.add(txtProductRate.getText());
            
            v.add(Double.parseDouble(txtProductQty.getText()) * Double.parseDouble(txtProductRate.getText()));
            main.addRow(v);
            
            txtProductID.setText(null);
            txtProductName.setText(null);
            txtProductQty.setText(null);
            txtProductRate.setText(null);
         maintot = 0 ;
            for (int i = 0; i < main.getRowCount(); i++) {
                maintot += Double.parseDouble(main.getValueAt(i, 4).toString());
            }
          lblTotalAmount.setText((maintot+Double.parseDouble(txtExpenceTot.getText()))+"");
            txtRemain.setText(maintot+"");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Adding this record is incomplete."
                    + "\nRow is not added to the table", "Incomplete", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
           DefaultTableModel other  =  (DefaultTableModel) tOther.getModel();
            Vector v = new Vector();
            v.add(cmbType.getSelectedItem());
            v.add(txtOtherName.getText());
            v.add(txtOtherAmount.getText());
             
            other.addRow(v);
            
            txtOtherAmount.setText(null);
            txtOtherName.setText(null);
             othertot = 0 ;
            for (int i = 0; i < other.getRowCount(); i++) {
                othertot += Double.parseDouble(other.getValueAt(i, 2).toString());
            }
            txtExpenceTot.setText(othertot+"");
            lblTotalAmount.setText((maintot+othertot)+"");
            txtRemain.setText((maintot+othertot)+"");       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Adding this record is incomplete."
                    + "\nRow is not added to the table", "Incomplete", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 String ind = ((JTextField) txtDate.getDateEditor().getUiComponent()).getText();
        
        DefaultTableModel maint = (DefaultTableModel) tMain.getModel();
         DefaultTableModel expent = (DefaultTableModel) tOther.getModel();
      DefaultTableModel setttledt = (DefaultTableModel) tSettled.getModel();
        
        try {
             Statement s = main.DB.con().createStatement();
            Statement s1 = main.DB.con().createStatement();
            Statement s2 = main.DB.con().createStatement();
            Statement s3 = main.DB.con().createStatement();
            Statement s4 = main.DB.con().createStatement();
            Statement s5 = main.DB.con().createStatement();
            Statement s6 = main.DB.con().createStatement();
            Statement s7 = main.DB.con().createStatement();
             Statement s8 = main.DB.con().createStatement();
              Statement s9 = main.DB.con().createStatement();
               Statement s10 = main.DB.con().createStatement();
              Statement s11 = main.DB.con().createStatement();
              
            // insert to voucher
          s.executeUpdate("INSERT INTO `sanasa`.`voucher` VALUES "
                  + "('"+txtVoucherID.getText()+"','"+txtVoucherNo.getText()+"',"
                  + "'"+txtContactID.getText()+"','"+ind+"',"
                  + "'"+main.Date_Time.getTime()+"','"+lblTotalAmount.getText()+"',"
                  + "'"+lblTotalAmount.getText()+"','no','"+txtDesc.getText()+"')");
            
           // main table inserting
            for (int i = 0; i < maint.getRowCount(); i++) {
                
                // inserting to voucher details
                 s1.executeUpdate("INSERT INTO `sanasa`.`voture_details` VALUES "
                         + "('"+maint.getValueAt(i, 0).toString()+"','"+txtVoucherID.getText()+"',"
                         + "'"+maint.getValueAt(i, 2).toString()+"',"
                         + "'"+maint.getValueAt(i,3).toString()+"','"+maint.getValueAt(i, 4).toString()+"',"
                         + "'"+main.Stock.getBatchNo(maint.getValueAt(i, 0).toString())+"')");
              
                 
                 // Updating Stock
                 s2.executeUpdate("UPDATE `sanasa`.`stock` SET `qty` = `qty`+'"+maint.getValueAt(i, 2).toString()+"',"
                         + " `bprice` = '"+maint.getValueAt(i, 3).toString()+"',"
                         + "`Date` = '"+main.Date_Time.getDate()+"',`time` = '"+main.Date_Time.getTime()+"'"
                         + " WHERE `batchNo`= '"+main.Stock.getBatchNo(maint.getValueAt(i, 0).toString())+"'"
                         + " and `Inventory_id` = '"+maint.getValueAt(i, 0).toString()+"'");
            }
          
             for (int i = 0; i < expent.getRowCount(); i++) {
                
                // inserting to expence details
                 s3.executeUpdate("INSERT INTO `sanasa`.`expence_details` VALUES"
                         + " ('"+txtVoucherID.getText()+"','"+expent.getValueAt(i, 0).toString()+"',"
                         + "'"+expent.getValueAt(i, 1).toString()+"','"+expent.getValueAt(i, 2).toString()+"')");
                      
               }
             
             // inserting to personal Accounts
             double newBalance = main.Personal_Accounts.getBalance(txtContactID.getText()) + Double.parseDouble(lblTotalAmount.getText());
             s4.executeUpdate("INSERT INTO `sanasa`.`personal_account` VALUES"
                     + " ('0','"+txtContactID.getText()+"','"+main.Date_Time.getDate()+"',"
                     + "'"+main.Date_Time.getTime()+"','"+newBalance+"','"+txtVoucherID.getText()+"',"
                     + "'voucher','credit','"+(main.Personal_Accounts.getSequence()+1)+"' , 'none')");
             
            JOptionPane.showMessageDialog(this, "Voucher added !");
             if (Double.parseDouble(txtFnlSettled.getText())>0) {
              // update Voucher 
                s5.executeUpdate("UPDATE `sanasa`.`voucher` SET `Balance` = "
                        + "'"+txtRemain.getText()+"',`Status` = '"+lblVoucherStatus.getText()+"'"
                        + " WHERE `auto_id` = '"+txtVoucherID.getText()+"'");
            
            for (int i = 0; i < setttledt.getRowCount(); i++) {
                
                // Insert to voucher pays invoice
                s6.executeUpdate("INSERT INTO `sanasa`.`voucher_pays_invoice` "
                        + "VALUES ('"+txtVoucherID.getText()+"','"+setttledt.getValueAt(i, 0).toString()+"'"
                        + ",'"+setttledt.getValueAt(i, 2).toString()+"','"+main.Date_Time.getDate()+"',"
                        + "'"+main.Date_Time.getTime()+"')");
                
                if (setttledt.getValueAt(i, 3).toString().equals("full")) {
                    
                    // update Invoice
                   s6.executeUpdate("UPDATE `sanasa`.`invoice` SET `status` = 'ok',"
                           + "`balance` = '0',`mod_Date` = '"+main.Date_Time.getDate()+"',"
                           + "`mod_Time` = '"+main.Date_Time.getTime()+"' "
                           + "WHERE `auto_id` = '"+setttledt.getValueAt(i, 0).toString()+"'");
                   
                 
                    
                }else if (setttledt.getValueAt(i, 3).toString().equals("half")) {
                    
                    // update Invoice
                   s7.executeUpdate("UPDATE `sanasa`.`invoice` SET "
                           + "`balance` = `balance`-'"+Double.parseDouble(setttledt.getValueAt(i, 2).toString())+"',"
                           + "`mod_Date` = '"+main.Date_Time.getDate()+"',"
                           + "`mod_Time` = '"+main.Date_Time.getTime()+"' WHERE "
                           + "`auto_id` = '"+setttledt.getValueAt(i, 0).toString()+"'");
                   
                   
                }
               
            }
             JOptionPane.showMessageDialog(this,
                        "Voucher Successfully added and Invoice Settlement(s)  done ! ", 
                        "Complete" , JOptionPane.INFORMATION_MESSAGE); 
             }
            
       
            clear();
            startup();
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtContactIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactIDKeyReleased
         try {
            Statement st = main.DB.con().createStatement();
            ResultSet rs = st.executeQuery("SELECT `name` FROM `sanasa`.`contact`"
                    + " WHERE `nic`='"+txtContactID.getText()+"'");

            if (rs.next()) {
                txtContactName.setText(rs.getString(1));
                 } 
            loadTable ();
                  } catch (Exception ex) {
            ex.printStackTrace();
    }//GEN-LAST:event_txtContactIDKeyReleased
    }
    private void txtMeterialIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMeterialIDKeyReleased
        try {
            if (txtMeterialID.getText().isEmpty()) {
                  txtMeterialID.setText(null);
        txtMeterialName.setText(null);
        txtMeterialRate.setText(null);
        txtMeterialQty.setText(null);
            }else{
             Statement st = main.DB.con().createStatement();
//             Statement st1 = main.DB.con().createStatement();
            ResultSet rs = st.executeQuery("SELECT `name`,`subname`,`type` FROM "
                    + "`sanasa`.`inventory` WHERE `id`='"+txtMeterialID.getText()+"'");

//             ResultSet rs1 = st1.executeQuery("SELECT `bprice` FROM "
//                    + "`sanasa`.`stock` WHERE `Inventory_id`='"+txtMeterialID.getText()+"'");
            if (rs.next()) {
                txtMeterialName.setText(rs.getString(1)+"-"+rs.getString(2)+"-"+rs.getString(3));
                 } 
//             if (rs1.next()) {
                txtMeterialRate.setText(main.Stock.BPrice(txtMeterialID.getText())+"");
//                 } 
            
            }
            
           
                  } catch (Exception ex) {
            ex.printStackTrace();
    } 
    }//GEN-LAST:event_txtMeterialIDKeyReleased

    private void txtProductIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductIDKeyReleased
       try {
           if (txtProductID.getText().isEmpty()) {
                  txtProductID.setText(null);
        txtProductName.setText(null);
        txtProductQty.setText(null);
        txtProductRate.setText(null);
            }else{
            Statement st = main.DB.con().createStatement();
//             Statement st1 = main.DB.con().createStatement();
            ResultSet rs = st.executeQuery("SELECT `name`,`subname`,`type` FROM"
                    + " `sanasa`.`inventory` WHERE `id`='"+txtProductID.getText()+"'");

//              ResultSet rs1 = st1.executeQuery("SELECT `bprice` FROM "
//                    + "`sanasa`.`stock` WHERE `inventory_id`='"+txtProductID.getText()+"'");
            if (rs.next()) {
                txtProductName.setText(rs.getString(1)+"-"+rs.getString(2)+"-"+rs.getString(3));
                 } 
//            if (rs1.next()) {
                txtProductRate.setText(main.Stock.BPrice(txtProductID.getText())+"");
//                 }
           }
           
                  } catch (Exception ex) {
            ex.printStackTrace();
    } 
    }//GEN-LAST:event_txtProductIDKeyReleased

    private void txtContactIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactIDActionPerformed

    private void tOtherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tOtherKeyPressed
        DefaultTableModel dtm = (DefaultTableModel) tOther.getModel();
        try {
           if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                lblTotalAmount.setText((Double.parseDouble(lblTotalAmount.getText())
                        - Double.parseDouble(dtm.getValueAt(tOther.getSelectedRow(), 2).toString()))+"");
                
                  txtRemain.setText((Double.parseDouble(txtRemain.getText())
                        - Double.parseDouble(dtm.getValueAt(tOther.getSelectedRow(), 2).toString()))+"");
                  
                txtExpenceTot.setText((Double.parseDouble(txtExpenceTot.getText())
                        - Double.parseDouble(dtm.getValueAt(tOther.getSelectedRow(), 2).toString()))+"");
                
            dtm.removeRow(tOther.getSelectedRow());
          
        }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Row can't be deleted !");
            e.printStackTrace();
        }
  
       
    }//GEN-LAST:event_tOtherKeyPressed

    private void tMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tMainKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) tMain.getModel();
        try {
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                 lblTotalAmount.setText((Double.parseDouble(lblTotalAmount.getText())
                        - Double.parseDouble(dtm.getValueAt(tMain.getSelectedRow(), 4).toString()))+"");
                 
                 txtRemain.setText((Double.parseDouble(txtRemain.getText())
                        - Double.parseDouble(dtm.getValueAt(tMain.getSelectedRow(), 4).toString()))+"");
                 
               maintot = maintot - Double.parseDouble(dtm.getValueAt(tMain.getSelectedRow(), 4).toString());
               dtm.removeRow(tMain.getSelectedRow());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Row can't be deleted !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_tMainKeyReleased

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
Statement s = main.DB.con().createStatement();
            if (JOptionPane.showConfirmDialog(this, "Are you Sure ?") == 0) {
                String type = JOptionPane.showInputDialog(this, "Enter new Type : ");
                if (type.isEmpty()) {
                    //                    cmbType.getMaddItem(type);
                }
                s.executeUpdate("INSERT INTO `sanasa`.`expence_type` VALUES ('"+type+"')");
                getExType ();
 //JOptionPane.showMessageDialog(this, "Adionistrator login required !");
            }

        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            DefaultTableModel settle = (DefaultTableModel) tPrevious.getModel();
             DefaultTableModel settled = (DefaultTableModel) tSettled.getModel();
            String invoiceNo = settle.getValueAt(tPrevious.getSelectedRow(), 0).toString();
            String amount = JOptionPane.showInputDialog(this,"Invoice ID : "+invoiceNo ,
                    "Enter settling amount", JOptionPane.QUESTION_MESSAGE);
            if (amount.isEmpty()) {
                throw new NumberFormatException() ;
            }
            Vector v = new Vector();
            v.add(settle.getValueAt(tPrevious.getSelectedRow(), 0));
             v.add(settle.getValueAt(tPrevious.getSelectedRow(), 1));
             v.add(amount);
             
             if (Double.parseDouble(settle.getValueAt(tPrevious.getSelectedRow()
                     ,3).toString()) == Double.parseDouble(amount)) {
                 v.add("full");
            }else if(Double.parseDouble(settle.getValueAt(tPrevious.getSelectedRow()
                     , 3).toString()) > Double.parseDouble(amount)){
                v.add("half");
        }else{
                
                v.add("Over paid");
                throw new Exception();
            }
             
             settled.addRow(v);
             
             txtSettledCount.setText(settled.getRowCount()+"");
             double tot = 0;
             for (int i = 0; i < settled.getRowCount(); i++) {
                tot += Double.parseDouble(settled.getValueAt(i, 2).toString());
            }
             txtSettledAmount.setText(tot+"");
             settle.removeRow(tPrevious.getSelectedRow());
                            } 
        catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Amount !");
            e.printStackTrace();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Over Paid Invoice ! try again later");
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
        if (JOptionPane.showConfirmDialog(this, "Are you Sure ?" , "Confirm" , JOptionPane.OK_CANCEL_OPTION) == 0) {
            if (Double.parseDouble(lblTotalAmount.getText()) >= Double.parseDouble(txtSettledAmount.getText())) {
                txtFnlSettled.setText(txtSettledAmount.getText());
            txtRemain.setText((Double.parseDouble(lblTotalAmount.getText())
                    -Double.parseDouble(txtFnlSettled.getText()))+""); 
                if (Double.parseDouble(txtRemain.getText())==0) {
                    lblVoucherStatus.setText("yes");
                }else if(Double.parseDouble(txtRemain.getText())>0) {
                    lblVoucherStatus.setText("no");
                }else { lblVoucherStatus.setText("error");}
            }else {
            JOptionPane.showMessageDialog(this, "Voucher Not enough !. Invoices are Over Settled !");
            }
   
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tSettledKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSettledKeyPressed
        DefaultTableModel dtm = (DefaultTableModel) tSettled.getModel();
        try {
           if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
           
            txtSettledAmount.setText((Double.parseDouble(txtSettledAmount.getText())
                        - Double.parseDouble(dtm.getValueAt(tSettled.getSelectedRow(), 2).toString()))+"");
             dtm.removeRow(tSettled.getSelectedRow());
             txtSettledCount.setText((Integer.parseInt(txtSettledCount.getText())-1)+"");
           }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_tSettledKeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       loadTable ();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       if (JOptionPane.showConfirmDialog(this, "This will create new Batch. Are you Sure ?" , "Confirm" , JOptionPane.OK_CANCEL_OPTION) == 0) {
        String pamount = JOptionPane.showInputDialog(this,"Enter New Buying Price :", JOptionPane.QUESTION_MESSAGE);
        
       txtProductRate.setText(pamount);
        try {
                Statement s1 = main.DB.con().createStatement();
                s1.executeUpdate("INSERT INTO `sanasa`.`stock` "
                        + "VALUES ('"+txtProductID.getText()+"','0',"
                        + "'0','"+txtProductRate.getText()+"',"
                        + "'"+main.Stock.getSprice (txtProductID.getText())+"','"+main.Date_Time.getDate()+"',"
                        + "'"+main.Date_Time.getTime()+"','"+(main.Stock.getBatchNo(txtProductID.getText())+1)+"')");
                JOptionPane.showMessageDialog(this, "New Batch Successfully Added !");
           } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Adding new Batch was failed", "error" , JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();  
           }
          
       
       }       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      if (JOptionPane.showConfirmDialog(this, "This will create new Batch. Are you Sure ?" , "Confirm" , JOptionPane.OK_CANCEL_OPTION) == 0) {
        String mamount = JOptionPane.showInputDialog(this,"Enter New Buying Price :", JOptionPane.QUESTION_MESSAGE);
      txtMeterialRate.setText(mamount);
         try {
                Statement s1 = main.DB.con().createStatement();
                s1.executeUpdate("INSERT INTO `sanasa`.`stock` "
                        + "VALUES ('"+txtMeterialID.getText()+"','0',"
                        + "'0','"+txtMeterialRate.getText()+"',"
                        + "'"+main.Stock.getSprice (txtMeterialID.getText())+"','"+main.Date_Time.getDate()+"',"
                        + "'"+main.Date_Time.getTime()+"','"+(main.Stock.getBatchNo(txtMeterialID.getText())+1)+"')");
                JOptionPane.showMessageDialog(this, "New Batch Successfully Added !");
           } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Adding new Batch was failed", "error" , JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();  
           }
      }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed
            /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblVoucherStatus;
    private javax.swing.JTable tMain;
    private javax.swing.JTable tOther;
    private javax.swing.JTable tPrevious;
    private javax.swing.JTable tSettled;
    private javax.swing.JTextField txtContactID;
    private javax.swing.JTextField txtContactName;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtExpenceTot;
    private javax.swing.JTextField txtFnlSettled;
    private javax.swing.JTextField txtMeterialID;
    private javax.swing.JTextField txtMeterialName;
    private javax.swing.JTextField txtMeterialQty;
    private javax.swing.JTextField txtMeterialRate;
    private javax.swing.JTextField txtOtherAmount;
    private javax.swing.JTextField txtOtherName;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductQty;
    private javax.swing.JTextField txtProductRate;
    private javax.swing.JTextField txtRemain;
    private javax.swing.JTextField txtSettledAmount;
    private javax.swing.JTextField txtSettledCount;
    private javax.swing.JTextField txtVoucherID;
    private javax.swing.JTextField txtVoucherNo;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        txtFnlSettled.setText(null);
        txtExpenceTot.setText(null);
        txtContactID.setText(null);
        txtContactName.setText(null);
       
        txtVoucherID.setText(null);
        txtVoucherNo.setText(null);
        txtMeterialID.setText(null);
        txtMeterialName.setText(null);
        txtMeterialRate.setText(null);
        txtMeterialQty.setText(null);
        txtProductID.setText(null);
        txtProductName.setText(null);
        txtProductQty.setText(null);
        txtProductRate.setText(null);
        txtOtherName.setText(null);
        txtOtherAmount.setText(null);
        txtRemain.setText(null);
        lblTotalAmount.setText("0000");
        
        DefaultTableModel main  =  (DefaultTableModel) tMain.getModel();
        DefaultTableModel other  =  (DefaultTableModel) tOther.getModel();
        DefaultTableModel previous  =  (DefaultTableModel) tPrevious.getModel();
        DefaultTableModel settle  =  (DefaultTableModel) tSettled.getModel();
        main.setRowCount(0);
        other.setRowCount(0);
        previous.setRowCount(0);
        settle.setRowCount(0);
    }
    ArrayList<String> id , name , metId , metName , proId , ProName ;
    private void startup() {
                  
   
        id = new ArrayList<String>();
        name = new ArrayList<String>();
        metId = new ArrayList<String>();
         metName = new ArrayList<String>();
          proId = new ArrayList<String>();
           ProName = new ArrayList<String>();
        try {
            Statement s = main.DB.con().createStatement();
            Statement s1 = main.DB.con().createStatement();
           Statement s2 = main.DB.con().createStatement();
           Statement s3 = main.DB.con().createStatement();
          
            ResultSet rs5 = s.executeQuery("SELECT `auto_id`  FROM `sanasa`.`voucher` ORDER BY `auto_id` desc");
            int vid = 0 ;
            if (rs5.next()) {
              vid = Integer.parseInt(rs5.getString(1).substring(3));
            }
           vid ++ ;
           txtVoucherID.setText("VOU"+vid);
            ResultSet rs = s.executeQuery("SELECT `nic`,`name` FROM `sanasa`.`contact`");
            while (rs.next()) {
                id.add(rs.getString(1));
                name.add(rs.getString(2));
            }

            ResultSet rs2 = s1.executeQuery("SELECT `id`,`name`,`subname`,`type` FROM `sanasa`.`inventory`");
            while (rs2.next()) {
                metId.add(rs2.getString(1));
                metName.add(rs2.getString(2)+"-"+rs2.getString(3)+"-"+rs2.getString(4));
            }
           
             ResultSet rs3 = s2.executeQuery("SELECT `id`,`name`,`subname`,`type` FROM `sanasa`.`inventory`");
            while (rs3.next()) {
                proId.add(rs3.getString(1));
                ProName.add(rs3.getString(2)+"-"+rs3.getString(3)+"-"+rs3.getString(4));
            }
            main.AutoComplete.setupAutoComplete(txtContactID, id);
            main.AutoComplete.setupAutoComplete(txtContactName, name);
             main.AutoComplete.setupAutoComplete(txtMeterialID, metId);
            main.AutoComplete.setupAutoComplete(txtMeterialName, metName);
             main.AutoComplete.setupAutoComplete(txtProductID, proId);
            main.AutoComplete.setupAutoComplete(txtProductName, ProName);
            
            getExType();
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Auto Complete Loading Error");
            e.printStackTrace();
        }
    }

    private void loadTable() {
         DefaultTableModel dtm = (DefaultTableModel) tPrevious.getModel();
    dtm.setRowCount(0);
    
        String getInvoice = "SELECT `auto_id` , `date`,balance ,`maintotal`,no FROM "
                + "`sanasa`.`invoice` WHERE `status`='no' AND `Contact_nic`='"+txtContactID.getText()+"'";
      
        try {
            Statement s1 = main.DB.con().createStatement();
                   
            ResultSet rs = s1.executeQuery(getInvoice);
            
            while (rs.next()) {
                Vector v = new Vector();
               
                v.add(rs.getString(1));
                 v.add(rs.getString(5));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                 v.add(rs.getString(4));
              dtm.addRow(v);
            }
            
            
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
        
    }

   private void getExType() {
        try {
            cmbType.removeAllItems();
            Statement s = main.DB.con().createStatement();
            ResultSet rs = s.executeQuery("SELECT `name` FROM `sanasa`.`expence_type`");
            while (rs.next()) {                
                cmbType.addItem(rs.getString(1));
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }

   
     
    }

